services:

    EightMarq\CoreBundle\EventListener\BlameableEventListener:
        tags: [ 'doctrine.event_subscriber' ]
        arguments:
            $security: '@Symfony\Bundle\SecurityBundle\Security'

    EightMarq\CoreBundle\EventListener\TimestampableEventListener:
        tags: [ 'doctrine.event_subscriber' ]

    EightMarq\CoreBundle\EventListener\SoftDeleteableEventListener:
        tags: [ 'doctrine.event_subscriber' ]
